### ISSUE TITLE
Systemd support

### ISSUE THREAD

**Issue by poikilotherm** [rvdh/puppet-uwsgi#13]
Hi there,

I just started to work on systemd support as I wanted to run uWSGI on my RHEL7 system.

Feel free to take a look and drop some comments before I feel ready to create a PR:
https://github.com/poikilotherm/puppet-uwsgi/tree/feature/systemd_support

By the way: this fixes some lints, too. Did some minor refactoring, too...

Still todo: do a 'systemctl daemon-reload'...

**Comment by jarshwah** [comment]
Sorry I haven't responded here -- I'm bad at checking github notifications and didn't see an email associated with this issue. Your commit looks mostly good, but it'll be easier to test/check with a proper PR.

That said, I wouldn't mind handing over the reigns of this project. I'm happy to push systemd support through a release, but then I'll probably look to hand off maintenance of this project to someone else if I can, and if there's interest.

**Comment by jeff1evesque** [comment]
@jarshwah, perhaps you can add @poikilotherm as an admin to the repository, so he can merge the changes.

**Comment by jeff1evesque** [comment]
@jarshwah, perhaps adding @poikilotherm as admin to the repository, will allow changes to be merged, and maybe he'd help with future changes?
