### ISSUE TITLE
https://github.com/rvdh would like to take ownership of this repo

### ISSUE THREAD

**Issue by jarshwah** [rvdh/puppet-uwsgi#15]
Hey crew,

https://github.com/rvdh emailed me directly to ask if he could take ownership of this repo as I wasn't maintaining it much (at all) anymore. His fork is https://github.com/rvdh/puppet-uwsgi and has fixed systemd support on some systems.

If no one at Engage plans on maintaining this module, I'd suggest transferring ownership. It'll mean the "official" fork is registered under his user account.

As an alternative, you could create a new organisation for open source stuff, and add him as a contributor/admin.

Engage don't use puppet-uwsgi anywhere except to host the graphite module. The other webapps use manual uwsgi configuration (without emperor mode), where this module mostly focuses on running apps in emperor mode.

I'll link @rvdh to this issue so you can discuss with him directly. @adamtbeames or @noemif can you follow up please?

**Comment by noemif** [comment]
Hey @jarshwah !

Hope you're doing well :-)
Makes sense to transfer ownership as far as I'm concerned.

@rvdh: I'll run this past the rest of the crew on wednesday, it's a long weekend here and some of us are away.

Cheers,
Noemi

**Comment by bohdyone** [comment]
Seems fine to me too.

We can always continue what will become our fork if we need any further
changes for some reason.

**Comment by adamtbeames** [comment]
@noemif @bohdyone if we aren't actively using or maintaining anymore it makes sense to transfer ownership to @rvdh.

Do we have consensus?

**Comment by noemif** [comment]
Looks like we do have consensus :-)
@rvdh, I'll transfer ownership today.

**Comment by noemif** [comment]
hi @rvdh,

I have just transferred the repo out of organization (a pre-requisite to transfer to you).
I am unable to transfer ownership to you because of a name conflict with your own puppet-uwsgi" repo.

Are you able to rename the repo ?

Cheers,
Noemi

**Comment by rvdh** [comment]
@noemif Great! I've renamed the repository.

**Comment by noemif** [comment]
@rvdh gaaahhh ! now GitHub comes up with the message "rvdh already has a repository in the noemif/puppet-uwsgi network"... maybe it's not enough to rename the repo. Not sure what a GitHub  network is, will have to have a closer look.

**Comment by rvdh** [comment]
@noemif I deleted the fork, I will merge my changes manually when it's transferred. I think it should work now :).

**Comment by noemif** [comment]
@rvdh I've transferred the repo ownership again and just got an info message saying "Repository transfer to rvdh requested". So I assume you should get a request to approve the transfer  and we should be all set. pheeew :-)

**Comment by rvdh** [comment]
@noemif Looks like it worked! :) Thank you and @jarshwah and @adamtbeames :)

**Comment by noemif** [comment]
excellent ! Thank you for taking up maintenance of this repo.
have fun :-)
