### ISSUE TITLE
Using systemd, using "--die-on-term" causes very slow stops

### ISSUE THREAD

**Issue by TravellingGuy** [rvdh/puppet-uwsgi#21]
Using the `--die-on-term` option in the uwsgi_systemd.service.erb template causes the system to be painfully slow stopping the service (with `service uwsgi stop` or `systemctl stop uwsgi`). This is on Ubuntu 16.04 (Xenial).

The systemd service file that uwsgi recommends (http://uwsgi-docs.readthedocs.io/en/latest/Systemd.html) does not include `--die-on-term`. Based on the note on that page, it suggests that `--die-on-term` might have been used to workaround an issue with some older versions of systemd.

**Comment by poikilotherm** [comment]
Hi @TravellingGuy 

can you verify if this is still an issue with my newly released version, which is a major refactored module?

https://forge.puppet.com/poikilotherm/uwsgi

Cheers!

**Comment by TravellingGuy** [comment]
Hi @poikilotherm 

Sorry for the very late reply. The default is still broken, but I see I can now set the kill signal in configuration, so that fixes it for me.
